"""create table RevokedToken

Revision ID: 862b8d0b783c
Revises: 05b75b8b5a50
Create Date: 2023-11-03 15:08:12.801330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862b8d0b783c'
down_revision = '05b75b8b5a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
